name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build with esbuild
      run: npm run build

    - name: Zip files
      run: cd dist; zip -r ../dist.zip * ; cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist.zip

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: .

    - name: Deploy to AWS Lambda
      uses: embeddedinn/deploy_lambda@v1.0.0
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        lambda-name: node-lambda-testing
        zip-file: dist.zip
